name: GoFastProject
favicon: null
layout_spectrum: 0.03970393219756796
typography_spectrum: 0.804099586470745
title: The Go Fast Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70481627-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D8D0'
    - '#08707D'
    - '#988868'
    - '#18D8F0'
    - '#000000'
  brandStrength: 0.187633047328161
  lightness: 0.9140029923178176
  saturation: 0.4571418085848138
  rhythmicContrast: 0.14536712925685724
purpose:
  - name: null
    item: null
    url: null
