name: GoFastProject
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72607
title: The Go Fast Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70481627-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D8D0'
    - '#08707D'
    - '#988868'
    - '#18D8F0'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
