analytics:
  google: UA-70481627-1
color:
  brandColors:
    - '#D8D8D0'
    - '#08707D'
    - '#988868'
    - '#18D8F0'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.4375
cta: {}
layout_spectrum: 1
name: GoFastProject
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.72607
